# Le nom du workflow, tel qu'il apparaîtra dans l'onglet "Actions" de GitHub
name: Publish Docker Image

# Le bloc "on" définit QUAND ce workflow doit se déclencher
on:
  push:
    # On précise qu'on veut s'exécuter uniquement lors d'un commit (push) sur la branche "develop"
    branches:
      - develop

# Les "jobs" (tâches) que notre workflow va effectuer
jobs:
  #Nom de la tâche
  build-and-push:
    # On demande à GitHub de lancer ce job sur une machine virtuelle Linux (Ubuntu)
    runs-on: ubuntu-latest
    
    # === SOLUTION DE L'ERREUR DE PERMISSION ===
    # Par défaut, le GITHUB_TOKEN généré pour l'action ne peut que lire le code.
    # Pour pousser une image Docker dans l'organisation (GHCR), il lui faut la permission d'écriture.
    permissions:
      contents: read
      packages: write

    # Les différentes étapes (steps) exécutées séquentiellement sur la machine virtuelle
    steps:
      # 1. On utilise une Action officielle de GitHub pour télécharger notre code source sur la machine virtuelle
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Conversion du nom du dépôt en minuscules. 
      # Docker refuse les majuscules dans le tag des images, or votre pseudo "Akinaru" commence par une majuscule !
      # On stocke le résultat dans une variable d'environnement (REPO_LC) pour s'en servir plus bas.
      - name: Convert repository name to lowercase
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # 3. On se connecte au GitHub Container Registry (ghcr.io)
      # On utilise le GITHUB_TOKEN comme mot de passe.
      # L'utilisation de "echo ... | docker login --password-stdin" est plus sécurisée que d'écrire le mot de passe en clair.
      - name: Log in to GitHub Container Registry
        # github.actor sera remplacé automatiquement par votre nom d'utilisateur GitHub lors de l'exécution
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 4. On construit l'image Docker à partir de notre Dockerfile.
      # On utilise env.REPO_LC (notre variable en minuscules) pour le tag (-t)
      # Mais on garde github.repository (avec majuscules) pour le label, pour que le lien web GitHub reste parfait.
      - name: Build Docker image
        run: docker build --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" -t ghcr.io/${{ env.REPO_LC }}:staging .

      # 5. On pousse l'image nouvellement construite vers le registre en ligne.
      - name: Push Docker image
        run: docker push ghcr.io/${{ env.REPO_LC }}:staging
